name: extract_information_student_card_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.2+1
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  logger: ^2.6.1
  onnxruntime: ^1.4.1
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weights/
    - assets/images/
    - assets/weights/recognition/
